const opdrachten = {

    makkelijk: [

"Vraag iemand hoe zijn of haar dag was.",
"Vraag of iemand het eten lekker vindt.",
"Neem een slok drinken nadat iemand anders dat doet.",
"Kijk even naar buiten alsof je iets ziet.",
"Vraag wie het toetje heeft uitgekozen.",
"Noem één keer iemands naam tijdens een gesprek.",
"Vraag wat iemand morgen gaat doen.",
"Leg je vork even neer voordat je verder eet.",
"Kijk kort naar het plafond.",
"Vraag of iemand nog drinken wil.",
"Zeg één keer 'Dat is eigenlijk best logisch.'",
"Vraag wat iemands favoriete seizoen is.",
"Pak je glas met twee handen vast.",
"Vraag wie het vaakst kookt.",
"Leun tien seconden naar achteren.",
"Kijk even naar je bord voordat je antwoord geeft.",
"Vraag wie het eerst klaar is met eten.",
"Noem één keer het woord 'precies'.",
"Vraag of iemand een leuke serie kijkt.",
"Schuif je bord een klein stukje op.",
"Vraag wat iemand dit weekend gaat doen.",
"Neem een kleine pauze voordat je antwoord geeft.",
"Vraag wie vandaag het drukst was.",
"Noem één keer het woord 'toevallig'.",
"Vraag wat iemands favoriete drankje is.",
"Kijk vijf seconden naar je bestek.",
"Vraag of iemand nog honger heeft.",
"Zeg één keer 'Interessant...'.",
"Vraag wie het mooiste weer vindt: zomer of winter.",
"Veeg heel kort over de tafel alsof er een kruimel ligt."

],

    normaal: [

"Gebruik drie keer het woord 'eigenlijk' tijdens het eten.",
"Vraag twee verschillende mensen naar hun mening.",
"Zeg een keer: 'Dat had ik niet verwacht.'",
"Noem één keer een herinnering van vroeger.",
"Vraag wie het langst aan tafel blijft zitten.",
"Neem twee slokken drinken vlak na elkaar.",
"Kijk één persoon drie seconden aan terwijl hij praat.",
"Zeg één keer: 'Dat is een goede vraag.'",
"Vraag of iemand vandaag iets grappigs heeft meegemaakt.",
"Schuif ongemerkt je stoel een klein stukje naar achteren.",
"Gebruik twee keer het woord 'misschien'.",
"Vraag aan iemand of hij of zij nog honger heeft, ook al is het duidelijk.",
"Leg je handen tien seconden op tafel.",
"Vraag wie het vaakst de afwas doet.",
"Zeg één keer: 'Dat kan ook natuurlijk.'",
"Begin een zin met: 'Stel je voor...'",
"Vraag aan iemand wat hij als laatste heeft gekocht.",
"Gebruik drie zinnen achter elkaar die beginnen met 'Ik...'.",
"Vraag wie het laatst wakker was gisteren.",
"Neem een slok drinken voordat je antwoord geeft.",
"Vraag aan iemand wat zijn favoriete snack is.",
"Gebruik één keer het woord 'overigens'.",
"Vraag wie er het meest praat aan tafel.",
"Maak een opmerking over het weer.",
"Vraag of iemand nog vakantieplannen heeft.",
"Zeg één keer: 'Dat is wel toevallig.'",
"Vraag wie als eerste klaar is met eten.",
"Kijk kort naar je telefoon zonder hem te gebruiken.",
"Vraag iemand wat hij morgen als eerste gaat doen.",
"Zeg één keer: 'Daar zit wel iets in.'"

],

    chaos: [
"Begin drie verschillende zinnen met: 'Eerlijk gezegd...'",
"Vraag ineens of iemand gelooft in buitenaards leven.",
"Gebruik vijf keer het woord 'eigenlijk'.",
"Vraag aan tafel: 'Wat zouden jullie doen als je een miljoen won?'",
"Probeer iedereen één keer aan het lachen te maken.",
"Vraag wie het meest geheimen kan bewaren.",
"Begin een gesprek over een compleet willekeurig onderwerp.",
"Zeg één keer: 'Dat doet me ergens aan denken...'",
"Vraag wie het slimst aan tafel is.",
"Vraag of iemand liever nooit meer pizza of nooit meer friet zou eten.",
"Gebruik drie keer het woord 'opvallend'.",
"Vraag wie het vaakst te laat komt.",
"Vertel een kort, grappig verhaal van vroeger.",
"Vraag wie er volgens de groep het grappigst is.",
"Zeg één keer: 'Ik heb daar een theorie over.'",
"Vraag wie het langst zonder telefoon zou kunnen.",
"Vraag ineens wat ieders favoriete dier is.",
"Gebruik twee keer achter elkaar het woord 'absoluut'.",
"Vraag wie het beste kan liegen.",
"Vraag wie het meest competitief is.",
"Zeg één keer: 'Nu ik erover nadenk...'",
"Vraag aan iemand: 'Wat zou jij morgen doen als je vrij had?'",
"Gebruik vier keer het woord 'misschien'.",
"Vraag wie het vaakst iets kwijtraakt.",
"Begin een discussie over welk seizoen het beste is.",
"Vraag wie het meest koppig is.",
"Zeg één keer: 'Dat klinkt eigenlijk best logisch.'",
"Vraag wie het langst zou overleven op een onbewoond eiland.",
"Vraag iedereen wat hun favoriete film ooit is.",
"Sluit een antwoord af met: '...denk ik.'"
    ]

};
